name: Continuous Integration

on: [push]

jobs:
  build-jar:
    name: Build Effekt compiler and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Checkout Kiama fork for ScalaJS
      uses: actions/checkout@v2
      with:
        repository: b-studios/kiama
        ref: scala-js
        path: kiama

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: npm install amdefine

    - name: Install Kiama fork
      run: sbt publishLocal
      working-directory: kiama

    - name: Run tests and assemble jar file
      run: sbt clean assembly
      
    - name: Assemble fully optimized js file
      run: sbt effektJS/fullOptJS

  build-vscode:
    name: Build the VSCode extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g typescript
    - run: npm install -g vsce
    - run: npm install
      working-directory: dist/vscode
    - name: Package VSCode extension into .vsix file
      run: vsce package
      working-directory: dist/vscode
